export const storeProducts = [
  {
    id: 1,
    title: "Keke Multigusto For Cats 1 Kg",
    img: "../img/product-food-1.jpg",
    price: 60,
    brand: "Keke",
    type: "Dry Food",
    size: "1kg",
    description:
      "KEKÈ MULTIGUSTO RECIPE FOR CATS FROM 6 MONTHS ONWARDSKEKÈ RECIPE MULTIGUSTO IS SUITABLE FOR CATS WITH SUPERFINE PALATES FROM THE SIXTH MONTH ONWARDS. THE NUTRITIVE ELEMENTS ARE OF HIGH BIOLOGICAL VALUE AND GUARANTEE THE GROWTH AND MAINTENANCE OF ALL BREEDS OF CATS. THE CROQUETTES CONTAIN MEAT, FISH, VEGETABLES, OMEGA 3 AND OMEGA 6 AND ARE INTEGRATED WITH ESSENTIAL AMINO ACIDS SUCH AS TAURINE, LYSINE AND METHIONINE.KEKÈ MULTIGUSTO RECIPE IS A FOOD RICH IN FLAVORS AND DOES NOT CONTAIN ADDED SALT.",
    rating: "95%",
    inCart: false,
    count: 0,
    total: 0,
  },
  {
    id: 2,
    title: "Royal Canin FELINE CARE NUTRITION URINARY CARE CAT DRY FOOD 2 KG",
    img: "../img/product-food-2.jpg",
    price: 700,
    brand: "Royal Canin",
    type: "Dry Food",
    size: "2kg",
    description:
      "Expirable : No, Brand : Royal Canin, Grade : Regular, Packaging Type : Pouch, Food Texture : Pellets, Size : 2 kg, Lifestage : Adult, Food Flavor : Multi, Food Type : Dry Food",
    rating: "75%",
    inCart: false,
    count: 0,
    total: 0,
  },
  {
    id: 3,
    title: "Purina friskies Chicken Adult 1.7kg",
    img: "../img/product-food-3.jpg",
    price: 150,
    brand: "Purina",
    type: "Dry Food",
    size: "1.7kg",
    description:
      "Brand : Purina, Packaging Type : plastic bag, Food Type : Dry Food, Size : 1.7 KG, Species : Cats, Grade : Regular, Lifestage : Adult, Food Flavor : Chicken, Food Texture : Seeds, Are batteries needed to power the product or is this product a battery : No, Is this a Dangerous Good or a Hazardous Material, Substance or Waste that is regulated for transportation, storage, and/or disposal? : No, Expirable : Yes",
    rating: "60%",
    inCart: false,
    count: 0,
    total: 0,
  },
  {
    id: 4,
    title: "Purina friskies Meet, CHICKEN AND VEGETABLES Adult 1.7kg",
    img: "../img/product-food-4.jpg",
    price: 150,
    brand: "Purina",
    type: "Dry Food",
    size: "1.7kg",
    description:
      "Brand : Purina, Packaging Type : plastic bag, Food Type : Dry Food, Size : 1.7 KG, Species : Cats, Grade : Regular, Lifestage : Adult, Food Flavor : Chicken, Food Texture : Seeds, Are batteries needed to power the product or is this product a battery : No, Is this a Dangerous Good or a Hazardous Material, Substance or Waste that is regulated for transportation, storage, and/or disposal? : No, Expirable : Yes",
    rating: "80%",
    inCart: false,
    count: 0,
    total: 0,
  },
  {
    id: 5,
    title: "Birbu Multi Dry Food For Cats - 1 kg",
    img: "../img/product-food-5.jpg",
    price: 65,
    brand: "Birbu",
    type: "Dry Food",
    size: "1kg",
    description: "Brand: Birbu, Size: 1 kg, Food Texture: Crisps",
    rating: "98%",
    inCart: false,
    count: 0,
    total: 0,
  },
  {
    id: 6,
    title: "Leonardo Kitten Chicken For Cats, 2 Kg",
    img: "../img/product-food-6.jpg",
    price: 320,
    brand: "Leonardo",
    type: "Wet Food",
    size: "2kg",
    description:
      "Product Features: Kitten Is Particularly Easy To Digest Because It Contains More Fresh Poultry, As Well As Chia Seeds To Regulate The Gut. In The First Few Months Of A Kitten’S Life, Good Digestion Is Particularly Important For Wellbeing. Kitten Contains Provital, A Combination Of Active Ingredients From Natural Yeast Extracts, To Support And Strengthen The Immune Function. The ingredients: Brewers yeast. Especially rich in natural B vitamins, high-grade protein and valuable vital substances. Marine zooplankton 'krill'. Especially rich in healthy nutrients and vital substances such as omega-3-fatty acids, astaxanthin and natural enzymes. Rye malt: Many cats love the light roasted taste and natural malt aroma.",
    rating: "80%",
    inCart: false,
    count: 0,
    total: 0,
  },
  {
    id: 7,
    title: "Purina Friskies Whitefish And Tuna Sauce - 156 GM",
    img: "../img/product-food-7.jpg",
    price: 33,
    brand: "Purina",
    type: "Wet Food",
    size: "156g",
    description:
      "Brand: Purina, Package: Can, Food Type: Wet Food, Size: 156 Gm, Species: Cats, Food flavor: Multi, Food texture: Flaked",
    rating: "90%",
    inCart: false,
    count: 0,
    total: 0,
  },
  {
    id: 8,
    title: "Wet Food - Hairball Care (Pouches) Box Of 12X85G",
    img: "../img/product-food-8.jpg",
    price: 700,
    brand: "Royal Canin",
    type: "Wet Food",
    size: "85g*12",
    description:
      "Brand : Royal Canin, Grade : Regular, Packaging Type : Pouch, Food Texture : Liquid, Size : 85g, Lifestage : All Stages, Food Flavor : Multi, Food Type : Wet Food, Species : Cats",
    rating: "100%",
    inCart: false,
    count: 0,
    total: 0,
  },
  {
    id: 9,
    title:
      "Purina Felix Wet Cat Single Serve As Good As It Looks Tuna 100 g Sachet, Pack Of 20",
    img: "../img/product-food-9.jpg",
    price: 400,
    brand: "Felix",
    type: "Wet Food",
    size: "100g*20",
    description:
      "Purina Felix As Good as it Looks with Tuna in Jelly. Felix As Good as it Looks is a range of irresistible meals that look, smell and taste so delicious they're just like food you might have cooked yourself. Each recipe has tender pieces in succulent jelly for a tasty meal your cat can really get his teeth into they really do taste as good as they look.",
    rating: "85%",
    inCart: false,
    count: 0,
    total: 0,
  },
  {
    id: 10,
    title:
      "Procat Soft Chunks in Gravy with Beef And Liver Cat Food Pouch, 100g",
    img: "../img/product-food-10.jpg",
    price: 29,
    brand: "Procat",
    type: "Wet Food",
    size: "100g",
    description:
      "Brand: Procat, Type: Wet Food, Size: 100 gm, Species: Cat, Lifestage: Adult",
    rating: "67%",
    inCart: false,
    count: 0,
    total: 0,
  },
  {
    id: 11,
    title: "Mikki - Jingle Balls, Cat Toy",
    img: "../img/product-toy-1.jpg",
    price: 50,
    brand: "Mikki",
    type: "Toy",
    size: "",
    description: "Plastic ball cat toy with bells to entice interest and play",
    rating: "83%",
    inCart: false,
    count: 0,
    total: 0,
  },
  {
    id: 12,
    title: "Am Pets 3-1434 Cat Toy - Blue",
    img: "../img/product-toy-2.jpg",
    price: 110,
    brand: "Am Pets",
    type: "Toy",
    size: "",
    description:
      "Brand: Am Pets, Type: Pets Toys, Size: 25 X 35 cm, Circular Cat Toy With Ball, Brand: Am Pets, Type: Pets Toys, Size: 25 X 35 cm, Circular Cat Toy With Ball",
    rating: "70%",
    inCart: false,
    count: 0,
    total: 0,
  },
  {
    id: 13,
    title: "Three Levels pet cat toy Tower Tracks Disc",
    img: "../img/product-toy-3.jpg",
    price: 105,
    brand: "Other",
    type: "Toy",
    size: "",
    description:
      "Brand : Other, Species : Cats, Type : Toys, Sub Type : Interactive Toys",
    rating: "88%",
    inCart: false,
    count: 0,
    total: 0,
  },
  {
    id: 14,
    title: "Cat Toys With Mouse Shape Pet Bell Funny Cat Stick",
    img: "../img/product-toy-4.jpg",
    price: 50,
    brand: "Other",
    type: "Toy",
    size: "",
    description:
      "Brand : Other, Type : Toys, Sub Type : Interactive Toys, Species : Cats, Color:RandomPacking Content:1 x The Dangle Mouse Cat Toy , Are batteries needed to power the product or is this product a battery : No, Is this a Dangerous Good or a Hazardous Material, Substance or Waste that is regula, for transportation, storage, and/or disposal? : No",
    rating: "75%",
    inCart: false,
    count: 0,
    total: 0,
  },
  {
    id: 15,
    title: "Funny Stick Cat/Dog Laser Pointer Pen LED Light Toy - Blue",
    img: "../img/product-toy-5.jpg",
    price: 101,
    brand: "Other",
    type: "Toy",
    size: "",
    description:
      "High-quality LED light, very long service life , Very bright and very converging point better than the average Red Dot , This little red dot lights are lights function, good metal, quality , Very good pet toys, small cost big fun. , Cat and the owner will be playing the whole day. , You can shine on the wall on the floor, just move the cat will stop bashing grab ah , if there are big fat cats at .",
    rating: "95%",
    inCart: false,
    count: 0,
    total: 0,
  },
];

export const detailProduct = {
  id: 20,
  title: "Funny Stick Cat/Dog Laser Pointer Pen LED Light Toy - Blue",
  img: "../img/product-toy-5.jpg",
  price: 101,
  brand: "Other",
  type: "Toy",
  size: "1kg",
  description:
    "High-quality LED light, very long service life , Very bright and very converging point better than the average Red Dot , This little red dot lights are lights function, good metal, quality , Very good pet toys, small cost big fun. , Cat and the owner will be playing the whole day. , You can shine on the wall on the floor, just move the cat will stop bashing grab ah , if there are big fat cats at .",
  rating: "75%",
  inCart: false,
  count: 0,
  total: 0,
};
